project:
  type: website
  output-dir: docs

website:
  title: "Olaf Meneses"
  site-url: https://olafmeneses.github.io
  description: "Projects, thoughts and "
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: About
        href: index.qmd
      - icon: rss
        href: blog.xml

format:
  html:
    theme: 
      light: litera
      dark: vapor
    page-layout: full
    toc: true

editor: source

