project:
  type: website
  output-dir: docs

website:
  title: "Olaf Meneses"
  site-url: https://olafmeneses.com
  description: "Projects & thoughts"
  image: /images/profile/2x/profile.png
  favicon: /images/profile/2x/favicon.png
  twitter-card:
    creator: "@wooflaf"
  open-graph: true
  cookie-consent: true
  google-analytics: "G-DY78XYNR65"
  navbar:
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: About
        href: index.qmd
      - icon: rss
        href: blog/index.xml

format:
  html:
    theme: litera
    page-layout: full
    toc: true

editor: source

